version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    image: tiaradwim1306/node-app
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
  
volumes:
  mongo-db: